Collections:
- Name: AnimateDiff
  Paper:
    Title: 'AnimateDiff: Animate Your Personalized Text-to-Image Diffusion Models
      without Specific Tuning'
    URL: https://arxiv.org/abs/2307.04725
  README: configs/animatediff/README.md
  Task:
  - text2video
  Year: 2023
Models:
- Config: configs/animatediff/animatediff_ToonYou.py
  In Collection: AnimateDiff
  Name: animatediff_ToonYou
  Results:
  - Dataset: '-'
    Metrics: {}
    Task: Text2Video
  Weights: https://civitai.com/api/download/models/78775
- Config: configs/animatediff/animatediff_Lyriel.py
  In Collection: AnimateDiff
  Name: animatediff_Lyriel
  Results:
  - Dataset: '-'
    Metrics: {}
    Task: Text2Video
  Weights: https://civitai.com/api/download/models/72396
- Config: configs/animatediff/animatediff_RcnzCartoon.py
  In Collection: AnimateDiff
  Name: animatediff_RcnzCartoon
  Results:
  - Dataset: '-'
    Metrics: {}
    Task: Text2Video
  Weights: https://civitai.com/api/download/models/71009
- Config: configs/animatediff/animatediff_MajicMix.py
  In Collection: AnimateDiff
  Name: animatediff_MajicMix
  Results:
  - Dataset: '-'
    Metrics: {}
    Task: Text2Video
  Weights: https://civitai.com/api/download/models/79068
- Config: configs/animatediff/animatediff_RealisticVision.py
  In Collection: AnimateDiff
  Name: animatediff_RealisticVision
  Results:
  - Dataset: '-'
    Metrics: {}
    Task: Text2Video
  Weights: https://civitai.com/api/download/models/29460
